config/routes.rb
Stack::Application.routes.draw do
  get "sessions/new"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  resources :questions do
    resources :responses
  end

  resources :responses

  root 'questions#index'


end

app/models/question.rb
class Question < ActiveRecord::Base
  validates_presence_of :question
  belongs_to :user
  has_many :responses
end

app/models/response.rb
class Response < ActiveRecord::Base
  validates_presence_of :response
  belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_secure_password
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||=User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Please Login In" if current_user.nil?
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authorize, only: [:new, :create, :edit, :update]
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  def index
    @questions = Question.all
  end

  # GET /questions/1
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new

  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.js
      else
        format.html { render action: 'new' }
        format.js
      end
    end
  end

  # PATCH/PUT /questions/1
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /questions/1
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.js
    end
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question, :user_id)
    end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_filter :authorize, only: [:new, :create, :destroy]
  before_action :set_response, only: [:edit, :update, :destroy]

  def new

  end

  def create
    @question = Question.find(params[:question_id])
    @response = @question.responses.create(response_params)
    redirect_to question_path(@question)
  end

  def update
    @response.update(response_params)
    flash[:notice] = "Response favorited!"
    redirect_to("/questions/#{@response.question_id}")
  end

  def edit

  end

  def destroy

  end

  private
  def set_response
    @response = Response.find(params[:id])
  end

  def response_params
    params.require(:response).permit(:response, :askers_choice)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Invalid Email or Password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thanks for signing up!"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stack</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div id="user_header">
      <% if current_user %>
        Logged in as <%= current_user.email %>.
        <%= link_to "Log Out", logout_path %>
      <% else %>
        <%= link_to "Sign Up", signup_path %>
        <%= link_to "Log In", login_path %>
      <% end %>
    </div>


    <%= yield %>
  </div>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question, remote: true  do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<li id="question_<%= question.id %>"><a href="questions/<%= question.id %>"><%= question.question %></a>
        <%= link_to 'Edit', edit_question_path(question) %>
        <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></li>

app/views/questions/create.js.erb
$('#new_question').remove();
$('#new_link').show();
$('#question').append('<%= j render(@question) %>');

app/views/questions/destroy.js.erb
$('#question_<%= @question.id %>').remove();

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>SmackOverflow</h1>

<h4>Questions: </h4>

<ul id="question">
    <% @questions.each do |question| %>
        <li id=><a href="questions/<%= question.id %>"><%= question.question %></a>
        <%= link_to 'Edit', edit_question_path(question) %>
        <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></li>
    <% end %>
</ul>
<br>

<%= link_to 'New Question', new_question_path, id: "new_link", remote: true %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<p>Responses:</p>
<ol>
<% @question.responses.each do |response| %>
  <% if @question.user_id == current_user.id %>
      <li><%= response.response %> <%= radio_button_tag("response[askers_choice]", true, :onclick =>"response[askers_choice]") %> </li>
  <% else %>
    <li><%= response.response %> </li>
   <% end %>
 <% end %>
</ol>


<p>Add a Response:</p>
<%= render "responses/form" %>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/responses/_form.html.erb
<%= form_for([@question, @question.responses.build]) do |f| %>

  <div class="field">
    <%= f.label :response %><br>
    <%= f.text_field :response %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>